SyncfusionExamples/DocIO-Examples

Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-Framework/Convert-Word-document-to-PDF.sln
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-Framework/Convert-Word-document-to-PDF/App.config
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-Framework/Convert-Word-document-to-PDF/Convert-Word-document-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-Framework/Convert-Word-document-to-PDF/Program.cs
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-Framework/Convert-Word-document-to-PDF/Properties/AssemblyInfo.cs
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-Framework/Convert-Word-document-to-PDF/packages.config

Added .NET Framework sample for Word to PDF conversion.

Added .NET Framework sample for Word to PDF conversion

---

Table-Of-Contents/Customize-TOC-entries-style/.NET-Standard/Customize-TOC-entries-style.sln
Table-Of-Contents/Customize-TOC-entries-style/.NET-Standard/Customize-TOC-entries-style/Customize-TOC-entries-style.csproj
Table-Of-Contents/Customize-TOC-entries-style/.NET-Standard/Customize-TOC-entries-style/Program.cs

Added KB documentation samples. The sample is:
- Customize-TOC-entries-style

Adding sample of Table-Of-Contents

---

Charts/Create-100-stacked-area-chart/.NET-Standard/Create-100-stacked-area-chart.sln
Charts/Create-100-stacked-area-chart/.NET-Standard/Create-100-stacked-area-chart/Create-100-stacked-area-chart.csproj
Charts/Create-100-stacked-area-chart/.NET-Standard/Create-100-stacked-area-chart/Program.cs
Charts/Create-3D-100-stacked-area-chart/.NET-Standard/Create-3D-100-stacked-area-chart.sln
Charts/Create-3D-100-stacked-area-chart/.NET-Standard/Create-3D-100-stacked-area-chart/Create-3D-100-stacked-area-chart.csproj
Charts/Create-3D-100-stacked-area-chart/.NET-Standard/Create-3D-100-stacked-area-chart/Program.cs
Charts/Create-3D-area-chart/.NET-Standard/Create-3D-area-chart.sln
Charts/Create-3D-area-chart/.NET-Standard/Create-3D-area-chart/Create-3D-area-chart.csproj
Charts/Create-3D-area-chart/.NET-Standard/Create-3D-area-chart/Program.cs
Charts/Create-3D-stacked-area-chart/.NET-Standard/Create-3D-stacked-area-chart.sln
Charts/Create-3D-stacked-area-chart/.NET-Standard/Create-3D-stacked-area-chart/Create-3D-stacked-area-chart.csproj
Charts/Create-3D-stacked-area-chart/.NET-Standard/Create-3D-stacked-area-chart/Program.cs
Charts/Create-area-chart/.NET-Standard/Create-area-chart.sln
Charts/Create-area-chart/.NET-Standard/Create-area-chart/Create-area-chart.csproj
Charts/Create-area-chart/.NET-Standard/Create-area-chart/Program.cs
Charts/Create-stacked-area-chart/.NET-Standard/Create-stacked-area-chart.sln
Charts/Create-stacked-area-chart/.NET-Standard/Create-stacked-area-chart/Create-stacked-area-chart.csproj
Charts/Create-stacked-area-chart/.NET-Standard/Create-stacked-area-chart/Program.cs

Added KB documentation samples. The samples are:
- Create-area-chart
- Create-3D-area-chart
- Create-stacked-area-chart
- Create-100-stacked-area-chart
- Create-3D-100-stacked-area-chart
- Create-3D-stacked-area-chart

Adding Samples of area chart, 3D area chart, stacked area chart, 100% stacked area chart, 3d 100% stacked area chart, 3d stacked area chart in Charts

---

Charts/Create-3D-pie-chart/.NET-Standard/Create-3D-pie-chart.sln
Charts/Create-3D-pie-chart/.NET-Standard/Create-3D-pie-chart/Create-3D-pie-chart.csproj
Charts/Create-3D-pie-chart/.NET-Standard/Create-3D-pie-chart/Program.cs
Charts/Create-bar-of-pie-chart/.NET-Standard/Create-bar-of-pie-chart.sln
Charts/Create-bar-of-pie-chart/.NET-Standard/Create-bar-of-pie-chart/Create-bar-of-pie-chart.csproj
Charts/Create-bar-of-pie-chart/.NET-Standard/Create-bar-of-pie-chart/Program.cs
Charts/Create-pie-chart/.NET-Standard/Create-pie-chart.sln
Charts/Create-pie-chart/.NET-Standard/Create-pie-chart/Create-pie-chart.csproj
Charts/Create-pie-chart/.NET-Standard/Create-pie-chart/Program.cs

Added KB documentation samples. The samples are:
- Create-pie-chart
- Create-3D-pie-chart
- Create-bar-of-pie-chart

Adding sample of pie chart, 3D pie chart, bar of pie chart

---

Word-to-Image-conversion/Convert-Word-to-image/Blazor/Client-side-application/README.md
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Blazor/Client-side-application/README.md

Added README file for Blazor WASM application

---

Word-to-Image-conversion/Convert-Word-to-image/Blazor/Client-side-application/Convert-Word-to-Image/Convert-Word-to-Image.csproj
Word-to-Image-conversion/Convert-Word-to-image/Blazor/Client-side-application/README.md
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Blazor/Client-side-application/Convert-Word-to-PDF/Convert-Word-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Blazor/Client-side-application/README.md

- Enable property in project file.
- Added README file for Blazor WASM

Added README file for Blazor WASM

---

Charts/Create-volume-open-high-low-close/.NET-Standard/Create-volume-open-high-low-close.sln
Charts/Create-volume-open-high-low-close/.NET-Standard/Create-volume-open-high-low-close/Create-volume-open-high-low-close.csproj
Charts/Create-volume-open-high-low-close/.NET-Standard/Create-volume-open-high-low-close/Program.cs

Added KB sample. The sample is
- Create-volume-open-high-low-close

Adding sample of Volume-open-high-low-close chart

---

Sections/Add-default-header-and-footer/.NET-Framework/Add-default-header-and-footer.sln
Sections/Add-default-header-and-footer/.NET-Framework/Add-default-header-and-footer/Add-default-header-and-footer.csproj
Sections/Add-default-header-and-footer/.NET-Framework/Add-default-header-and-footer/App.config
Sections/Add-default-header-and-footer/.NET-Framework/Add-default-header-and-footer/Program.cs
Sections/Add-default-header-and-footer/.NET-Framework/Add-default-header-and-footer/Properties/AssemblyInfo.cs
Sections/Add-default-header-and-footer/.NET-Framework/Add-default-header-and-footer/packages.config

Added sample of Add-default-header-and-footer

Added sample of  Add-default-header-and-footer

---

Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Azure/Azure_App_Service/Convert-Word-Document-to-PDF/Controllers/HomeController.cs

Hi all,
Removed unwanted Lines from Azure App Service Sample
Regards
Venkatesh

Removed_unwanted_lines_from_Azure_App_Service_sample

---

Charts/Create-combination-chart/.NET-Standard/Create-combination-chart/Program.cs

Changed the code on program.cs to set secondary axis on right side.

Changed program.cs

---

Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET/Convert-Word-document-to-PDF.sln
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET/Convert-Word-document-to-PDF/Convert-Word-document-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET/Convert-Word-document-to-PDF/Program.cs

Added sample of Convert-Word-document-to-PDF in .NET 7.0

Added sample of Convert-Word-document-to-PDF

---

Find-and-Replace/Find-and-replace-text-with-image/WinForms/Find-and-replace-text-with-image/Form1.cs

Modified the code snippet of the Find-and-replace-text-with-image sample

Modified the code snippet of the Find-and-replace-text-with-image sample

---

Getting-Started/UWP/Create-Word-document/Create-Word-document.csproj

Hi All,
With this PR, we have resolved the security vulnerability issues in DocIO examples UWP project.

Resolved the security vulnerability issues in DocIO examples UWP project.

---

Getting-Started/ASP.NET-Core/Create-Word-Document/Create-Word-Document.csproj
Getting-Started/ASP.NET-MVC/Create-Word-document/packages.config
Getting-Started/ASP.NET/Create-Word-document/Create-Word-document.csproj
Getting-Started/ASP.NET/Create-Word-document/packages.config

Hi all,
With this PR, we have resolved the security vulnerability issues in DocIO Examples.
Regards,
Venkatesh

Task-843696 Clear security vulnerability issues in DocIO

---

Getting-Started/ASP.NET-MVC/Create-Word-document/packages.config
Getting-Started/ASP.NET/Create-Word-document/packages.config

Hi All,
1. Issue: Improper Handling of Exceptional Conditions in Newtonsoft.Json
2. Solution: Update the  bootstrap version
3. Reference : https://github.com/essential-studio/DocIO-Examples/security/dependabot/12
4. Changed in 2cs files

 Improper Handling of Exceptional Conditions in Newtonsoft.Json

---

Word-to-PDF-Conversion/Mutiple-Word-files-to-PDFs-and-zip/.NET/Mutiple-Word-files-to-PDFs-and-zip/Program.cs

Did the changes in comments in the sample

ES-848213 Sample to convert multiple Word documents to PDFs and zip the PDFs in C#

---

Getting-Started/.NET-MAUI/Create-Word-document/Platforms/MacCatalyst/SaveMac.cs
Getting-Started/.NET-MAUI/Create-Word-document/Platforms/iOS/SaveIOS.cs
Read-and-Save-document/Open-and-save-Word-document/.NET-MAUI/Open-and-save-Word-document/Platforms/MacCatalyst/SaveMac.cs
Read-and-Save-document/Open-and-save-Word-document/.NET-MAUI/Open-and-save-Word-document/Platforms/iOS/SaveIOS.cs
Word-to-Image-conversion/Convert-Word-to-image/.NET-MAUI/Convert-Word-Document-to-Image/Platforms/MacCatalyst/SaveMac.cs
Word-to-Image-conversion/Convert-Word-to-image/.NET-MAUI/Convert-Word-Document-to-Image/Platforms/iOS/SaveIOS.cs
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-MAUI/Convert-Word-Document-to-PDF/Platforms/MacCatalyst/SaveMac.cs
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/.NET-MAUI/Convert-Word-Document-to-PDF/Platforms/iOS/SaveIOS.cs

Hi All,
Modify the code for save mac and IOS in .NET MAUI Samples.
Regards,
Venkatesh

Modify the  code for save mac and IOS in .NET MAUI Samples

---

Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/Controllers/Word_To_PDF_Web_APIController.cs
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/Program.cs
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/Properties/launchSettings.json
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/Word_To_PDF_Web_API.csproj
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/Word_To_PDF_Web_API.csproj.user
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/Word_To_PDF_Web_API.sln
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/appsettings.Development.json
Word-to-PDF-Conversion/Word_To_PDF_Web_API/ASP.NET Core/appsettings.json

Sample for Word_To_PDF_Web_API using Swagger

Sample for Word_To_PDF_Web_API using Swagger

---

Charts/Create-chart-from-scratch/.NET-Standard/Create-chart-from-scratch/Program.cs
Charts/Remove-chart-title/.NET Standard/Remove-chart-title.sln
Charts/Remove-chart-title/.NET Standard/Remove-chart-title/Program.cs
Charts/Remove-chart-title/.NET Standard/Remove-chart-title/Remove-chart-title.csproj
Charts/Remove-chart-title/README.md

Added sample to remove default chart title from the Word document

ES-259583 Sample to remove default chart title from the Word document

---

HTML-conversions/Export-HTML-with-body-content/.NET/Export-HTML-with-body-content.sln
HTML-conversions/Export-HTML-with-body-content/.NET/Export-HTML-with-body-content/Export-HTML-with-body-content.csproj
HTML-conversions/Export-HTML-with-body-content/.NET/Export-HTML-with-body-content/Program.cs

Added sample for HTMLExportBodyContentAlone API

ES-865560 - Added sample for HTMLExportBodyContentAlone API

---

Mathematical-Equation/Apply-math-justification/Apply-math-justification.sln
Mathematical-Equation/Apply-math-justification/Apply-math-justification/Apply-math-justification.csproj
Mathematical-Equation/Apply-math-justification/Apply-math-justification/Program.cs

Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/868758
Added sample for applying math Justification

ES-868758 - Apply math justification sample

---

Fields/Insert-Multiple-Body-items-inside-IF-field/.NET/Insert-Multiple-Body-items-inside-IF-field.sln
Fields/Insert-Multiple-Body-items-inside-IF-field/.NET/Insert-Multiple-Body-items-inside-IF-field/Insert-Multiple-Body-items-inside-IF-field.csproj
Fields/Insert-Multiple-Body-items-inside-IF-field/.NET/Insert-Multiple-Body-items-inside-IF-field/Program.cs
Fields/Insert-Multiple-Body-items-inside-IF-field/README.md
Fields/Merge-field-inside-IF-field/.NET/Merge-field-inside-IF-field/Program.cs

Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/867984
Added sample for inserting multiple body items inside a IF field

ES-867984 - Added sample for inserting multiple body items inside a IF field

---

Word-to-PDF-Conversion/Reduce-pdf-size/.NET Framework/Reduce-pdf-size/Program.cs

Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/261884

ES-261884 - Removed unwanted changes

---

Word-document/Modify-built-in-document-properties/.NET-Standard/Modify-built-in-document-properties/Program.cs

Modify built-in document properties in Word document

Modify built-in document properties in Word document

---

Word-document/Set-page-field-for-each-section/.NET-Framework/Set-page-field-for-each-section.sln
Word-document/Set-page-field-for-each-section/.NET-Framework/Set-page-field-for-each-section/App.config
Word-document/Set-page-field-for-each-section/.NET-Framework/Set-page-field-for-each-section/Program.cs
Word-document/Set-page-field-for-each-section/.NET-Framework/Set-page-field-for-each-section/Properties/AssemblyInfo.cs
Word-document/Set-page-field-for-each-section/.NET-Framework/Set-page-field-for-each-section/Set-page-field-for-each-section.csproj
Word-document/Set-page-field-for-each-section/.NET-Framework/Set-page-field-for-each-section/packages.config
Word-document/Set-page-field-for-each-section/.NET/Set-page-field-for-each-section.sln
Word-document/Set-page-field-for-each-section/.NET/Set-page-field-for-each-section/Program.cs
Word-document/Set-page-field-for-each-section/.NET/Set-page-field-for-each-section/Set-page-field-for-each-section.csproj

Sample to Set-page-field-for-each-section

Sample to Set-page-field-for-each-section

---

Word-to-PDF-Conversion/Convert-5-pages-in-Word-to-PDF/.NET-Framework/Convert-5-pages-in-Word-to-PDF/App.config
Word-to-PDF-Conversion/Convert-5-pages-in-Word-to-PDF/.NET-Framework/Convert-5-pages-in-Word-to-PDF/Convert-5-pages-in-Word-to-PDF.csproj
Word-to-PDF-Conversion/Convert-5-pages-in-Word-to-PDF/.NET-Framework/Convert-5-pages-in-Word-to-PDF/packages.config

Convert-5-pages-in-Word-to-PDF

Convert-5-pages-in-Word-to-PDF

---

Getting-Started/Azure/Azure_App_Service/Create-Word-Document/Create-Word-Document.csproj
Read-and-Save-document/Open-and-save-Word-document/Azure/Azure_App_Service/Open_and_save_Word_document/Open_and_save_Word_document.csproj
Word-to-Image-conversion/Convert-Word-to-image/Azure/Azure_App_Service/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Azure/Azure_App_Service/Convert-Word-Document-to-PDF/Convert-Word-Document-to-PDF.csproj

Hi All,
Changed all the Azure App Service samples to .NET 8.0.
Regards,
Akash.

ES-909547 Update Azure platform GitHub demos to .NET 8.0 for Word Libraries

---

Getting-Started/Azure/Azure_Functions/Azure_Functions_v4/Create-Word-Document/Create-Word-Document.csproj
Read-and-Save-document/Open-and-save-Word-document/Azure/Azure_Functions/Azure_Functions_v4/Open-and-Save-Word-Document/Open-and-Save-Word-Document.csproj
Word-to-Image-conversion/Convert-Word-to-image/Azure/Azure_Functions/Azure_Functions_v4/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Azure/Azure_Functions/Azure_Functions_v4/Convert-Word-Document-to-PDF/Convert-Word-Document-to-PDF.csproj

Updated Azure functions platform GitHub demos to .NET 8.0 for DocIO library

909619-Update Azure functions platform GitHub demos to .NET 8.0 for DocIO library

---

Word-to-Image-conversion/Convert-Word-to-image/Azure/Azure_Functions/Azure_Functions_v1/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj

Updated Framework for Azure Function V1 Sample

Updated Framework for Azure Function V1 Sample

---

Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Linux/Convert-Word-Document-to-PDF/Convert-Word-Document-to-PDF.csproj

Modified the NuGet packages version for Word to PDF Linux sample

Modified the NuGet packages version for Word to PDF Linux sample

---

Bookmarks/Replace-content-with-document-part/.NET/Replace-content-with-document-part/README.md

Added Readme file for Replace bookmark content with Word document part sample.

Added Readme file for Replace bookmark content with Word document part sample

---

FAQs/Copy-fonts-to-linux-containers/Copy-fonts-to-linux-containers.csproj
Word-to-Image-conversion/Convert-Word-to-image/AWS/AWS_Elastic_Beanstalk/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-Image-conversion/Convert-Word-to-image/AWS/AWS_Lambda/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-Image-conversion/Convert-Word-to-image/Azure/Azure_App_Service/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-Image-conversion/Convert-Word-to-image/Blazor/Client-side-application/Convert-Word-to-Image/Convert-Word-to-Image.csproj
Word-to-Image-conversion/Convert-Word-to-image/Blazor/Client-side-application/README.md
Word-to-Image-conversion/Convert-Word-to-image/GCP/Google_App_Engine/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-Image-conversion/Convert-Word-to-image/Linux/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/AWS/AWS_Elastic_Beanstalk/Convert-Word-Document-to-PDF/Convert-Word-Document-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/AWS/MyLamdaProject/MyLamdaProject/MyLamdaProject.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Azure/Azure_App_Service/Convert-Word-Document-to-PDF/Convert-Word-Document-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Blazor/WASM-app/Convert-Word-to-PDF/Convert-Word-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Blazor/WASM-app/README.md
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Alpine/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/CentOS/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Debian/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Fedora/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/RHEL/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Ubuntu/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/GCP/Google-App-Engine/Convert-Word-document-to-PDF/Convert-Word-document-to-PDF.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Linux/Convert-Word-Document-to-PDF/Convert-Word-Document-to-PDF.csproj
Word-to-PDF-Conversion/Use-alternate-font-without-installing/Blazor/WASM-app/Use-alternate-font-without-installing/Use-alternate-font-without-installing.csproj

Description:
Changes in Skiasharp old version to new version.

ES-930475-Skiasharp version change

---

Getting-Started/.NET/Create-Word-document/Program.cs
Getting-Started/.NET/Create-Word-document/README.md

Description;
Code changes in Getting started Create Word document sample and README file.

Add README file in Getting started Create Word document sample

---

Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Alpine/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/CentOS/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Debian/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Fedora/WordToPDFDockerSample/WordToPDFDockerSample.csproj
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/Docker/Ubuntu/WordToPDFDockerSample/WordToPDFDockerSample.csproj

Hi Team,
I have added Harzburg SkiaSharp NuGet packages in all Docker projects on GitHub.
Regards,
Sivakumar. A

ES-944600-Update Harzburg SkiaSharp NuGet packages in all Docker projects on GitHub.

---

Word-to-Image-conversion/Convert-Word-to-image/AWS/AWS_Lambda/Convert-Word-Document-to-Image/Function.cs
Word-to-PDF-Conversion/Convert-Word-document-to-PDF/AWS/MyLamdaProject/MyLamdaProject/Function.cs

Description:
Removed the lines of code in  AWS-Lambda sample.

ES-958632- Changes in AWS-Lambda sample

---

Word-to-Image-conversion/Use-alternate-font-without-installing/.NET/Use-alternate-font-without-installing/Program.cs
Word-to-Image-conversion/Use-alternate-installed-font/.NET/Use-alternate-installed-font/Program.cs

Description:
Addressed the feedback in Word to image font substitution samples

ES-893200 - Address the feedback in Word to image font substitution samples

---

Getting-Started/Python-wrapper/Create-document/Create-document.sln
Getting-Started/Python-wrapper/Create-document/Create-document/Create-document.csproj
Getting-Started/Python-wrapper/Create-document/Create-document/CreateWordDocument.cs
Getting-Started/Python-wrapper/Python/CreateWordDocument.py

Description:
Added the sample in getting started for Python-Wrapper

ES-898646- Add the sample in getting started for Python-Wrapper
